######################################################################
# Automatically generated by qmake (3.0) Thu Oct 29 11:12:21 2015
######################################################################

QT+=widgets
TEMPLATE = app
TARGET = Project_589

# Input
HEADERS += renderer.h window.h \
    trackball.h \ 
    model.h \
    camera.h
SOURCES += main.cpp renderer.cpp window.cpp \
    trackball.cpp \ 
    model.cpp \
    camera.cpp
